import type { Slide } from './types'

/**
 * As telas do telão, na ordem fixa do CLAUDE.md §4. Não reordenar.
 *
 * Três telas dependem dos passos 4 a 6 da ordem de construção e estão aqui
 * como moldura: 13 (Wason), 17 (nuvem) e 30 (termômetro). Elas já ocupam o
 * lugar certo no roteiro para o deck rodar do começo ao fim.
 */
export const deck: Slide[] = [
  {
    id: '01',
    variant: 'eusei',
    text: 'EU SEI.',
    steps: 1,
    note: 'Já projetado quando eles entram. Entregue a ficha na porta, não diga o tema. Fica até 00:40.',
  },
  {
    id: '02',
    variant: 'claim',
    tag: 'Afirmação 1',
    text: 'Usamos apenas 10% do nosso cérebro.',
    steps: 1,
    note: 'Diga duas vezes, devagar. Espere todo mundo escrever, ~30s. Se alguém rir: "guarda" — sem sorrir de volta.',
  },
  {
    id: '03',
    variant: 'claim',
    tag: 'Afirmação 2',
    text: 'O aluno aprende mais quando o ensino é adaptado ao estilo de aprendizagem dele — visual, auditivo ou cinestésico.',
    steps: 1,
    note: 'A afirmação principal: é ela que volta no eixo e no termômetro. Duas vezes, devagar, sem expressão.',
  },
  {
    id: '04',
    variant: 'claim',
    tag: 'Afirmação 3',
    text: 'Sócrates nunca escreveu um livro.',
    steps: 1,
    note: 'É o Mênon disfarçado: a maioria acerta sem conseguir justificar. "Não sei nada sobre a 3" → "ótimo, confiança baixa e escreve não sei".',
  },
  {
    id: '05',
    variant: 'recap',
    tag: 'Mão para cima quem marcou verdadeiro',
    items: [
      'Usamos apenas 10% do nosso cérebro.',
      'O aluno aprende mais quando o ensino é adaptado ao estilo dele.',
      'Sócrates nunca escreveu um livro.',
    ],
    steps: 1,
    note: 'Conte em voz alta e anote. Cara de paisagem, não comente nenhum número. "Tá certo?" → "Depois."',
  },
  {
    id: '06',
    variant: 'axis',
    left: 'VERDADEIRO',
    right: 'FALSO',
    caption: 'o meio é "não faço ideia"',
    steps: 1,
    note: 'Todo mundo de pé. Só a afirmação 2. Diga "se posicionem" e FIQUE CALADO dez segundos. Você também entra na linha. Depois, maiêutica com três pessoas em pontos diferentes — você não corrige, você pergunta de onde veio. Tecla B abre as seis fontes.',
  },
  {
    id: '07',
    variant: 'mega',
    text: 'TROQUEM',
    foot: 'com alguém do lado oposto',
    steps: 1,
    note: 'Sem sair do lugar: escolham alguém do lado oposto, atravessem e troquem a folha. Deixe o caos por 15s.',
  },
  {
    id: '07b',
    variant: 'blank',
    steps: 1,
    note: 'Tela vazia de propósito — e clara, não preta. "Achem a linha como eu sei disso da afirmação 2. Leiam em silêncio." [10s] "A razão dela é pior que a sua?" [15s] "Devolvam." "Agora olhem a sua de novo." [3s de silêncio — não explique.]',
  },
  {
    id: '08',
    variant: 'two-line',
    lines: ['Os sentidos informam.', 'Mas o que eles garantem?'],
    steps: 2,
    note: 'Volte uma semana: no seminário passado os sentidos foram fonte de conhecimento, e foram mesmo. Depois: "mão para cima quem já achou que viu alguém conhecido na rua e não era".',
  },
  {
    id: '09',
    variant: 'illusion',
    steps: 2,
    note: 'Passo 1: os dois quadrados parecem tons diferentes. Passo 2: eles encostam — mesmo cinza, #8A8A8A. "Ver aconteceu. Só não bastou."',
  },
  {
    id: '10',
    variant: 'question',
    tag: 'Hipótese de correspondência',
    text: 'Adaptar o ensino ao estilo preferido faz aprender mais?',
    foot: 'preferências existem — a pergunta testada é outra',
    steps: 2,
    note: 'Separe o que está em jogo do que não está. Esta tela evita que o seminário vire "seu professor mentiu".',
  },
  {
    id: '11',
    variant: 'reference',
    authors: 'PASHLER, H.; McDANIEL, M.; ROHRER, D.; BJORK, R.',
    title: 'Learning Styles: Concepts and Evidence',
    where: 'Psychological Science in the Public Interest, v. 9, n. 3, p. 105–119, 2008.',
    steps: 1,
    note: '"Eu trouxe a fonte justamente para não pedir que vocês acreditem em mim." Procuraram estudos com o desenho adequado: quase não existiam, e os que existiam não sustentaram a hipótese.',
  },
  {
    id: '12',
    variant: 'two-line',
    lines: [
      'Não está provado que é falso.',
      'A crença é mais difundida que a evidência que a sustenta.',
    ],
    steps: 2,
    note: 'A frase mais importante do bloco — é ela que separa você de quem troca uma crença mal justificada por outra. Depois VOLTE AO EIXO (←) e pergunte "quem quer mudar de lugar?". Espere até 10s. Quando alguém se mover: não comente, não agradeça.',
  },
  {
    id: '13',
    variant: 'wason',
    seed: [2, 4, 6],
    tag: 'Estes três números obedecem a uma regra que eu tenho na cabeça',
    foot: 'mandem trios · eu respondo só sim ou não',
    steps: 1,
    note: 'Orçamento de 90 segundos. A regra real é qualquer sequência crescente. Quase sempre a turma supõe "soma de dois" e só manda trios que confirmam. Fecho: "vocês fizeram N testes, N−k deles só podiam dar sim" — liga na quinta pergunta do cartão. A lista ao vivo e o contador entram no passo 6.',
  },
  {
    id: '14',
    variant: 'dark-list',
    dark: true,
    items: [
      'Como você sabe?',
      'Quem te contou?',
      'Que evidência você tem?',
      'E se você estiver errado?',
      'Isso basta?',
    ],
    steps: 5,
    note: 'REVELAÇÃO. A turma está de pé. "Fiquem aí um segundo." Leia cada pergunta junto com a entrada dela, no mesmo ritmo. É a primeira tela preta do deck.',
  },
  {
    id: '15',
    variant: 'dark-two-line',
    dark: true,
    lines: ['Vocês passaram nove minutos fazendo isto.', 'Isto tem um nome.'],
    steps: 2,
    note: 'Decorado, palavra por palavra. As pausas fazem parte do texto.',
  },
  {
    id: '16',
    variant: 'dark-mega',
    dark: true,
    text: 'VOCÊ ACABOU DE FAZER EPISTEMOLOGIA',
    steps: 1,
    note: 'Três segundos de silêncio. Depois: "podem sentar". Não corte logo.',
  },
  {
    id: '17',
    variant: 'cloud',
    tag: 'Numa palavra: de onde veio o que você sabe?',
    steps: 1,
    note: '09:40 · 60 segundos, no máximo 15 palavras. Feche com: "isto na tela é uma lista de fontes de conhecimento — vocês acabaram de produzir uma". A nuvem ao vivo e o campo de digitação entram no passo 6.',
  },
  {
    id: '18',
    variant: 'two-line',
    lines: ['Não investiga o que sabemos.', 'Investiga o que faz contar como conhecimento.'],
    foot: 'epistemologia',
    steps: 2,
    note: 'A volta do preto para o claro é a segunda pancada. Deixe acontecer sem falar por um segundo.',
  },
  {
    id: '19',
    variant: 'axis',
    left: 'epistḗmē',
    right: 'dóxa',
    caption: 'conhecimento · opinião — o eixo que vocês atravessaram',
    foot: 'lógos — palavra, razão, e a conta que se dá',
    steps: 2,
    note: 'A palavra parece grega mas não é: foi cunhada em 1854 por James Ferrier. As raízes é que são gregas. Data e nome ficam só na fala.',
  },
  {
    id: '20',
    variant: 'triad',
    items: [
      { term: 'CRENÇA', gloss: 'você acredita' },
      { term: 'VERDADE', gloss: 'é o caso' },
      { term: 'JUSTIFICAÇÃO', gloss: 'você consegue dar conta' },
    ],
    steps: 3,
    note: '"Onde a gente falha mais?" — deixe responder — "justificação. As duas primeiras a gente resolve sozinho; a terceira é a única que precisa mostrar para alguém."',
  },
  {
    id: '21',
    variant: 'two-line',
    lines: ['Vocês acertaram.', 'Mas vocês sabiam?'],
    steps: 2,
    note: 'ANTES desta tela: revele falando que a 3 é verdadeira e pergunte POR QUÊ. Espere o silêncio. Só então avance.',
  },
  {
    id: '22',
    variant: 'tether',
    left: 'OPINIÃO VERDADEIRA',
    link: 'amarrada pela razão',
    right: 'CONHECIMENTO',
    foot: 'Platão, Mênon 97a–98a — guia tão bem quanto o conhecimento, enquanto fica',
    steps: 2,
    note: 'Quem chutou tem crença e verdade, e não tem justificação — é o problema do Mênon, e é por isso que a terceira peça existe. As estátuas de Dédalo saíam andando se ninguém amarrasse. "A resposta certa na prova prova o quê?"',
  },
  {
    id: '23',
    variant: 'optional',
    optional: true,
    tag: '1963 · coda opcional',
    text: 'Às vezes nem as três peças juntas bastam.',
    foot: 'Edmund Gettier, Is Justified True Belief Knowledge? — três páginas',
    steps: 1,
    note: 'OPCIONAL, oculta por padrão — ligue na janela de controle. Primeira coisa a cortar se atrasar. Gettier é o passo seguinte, não a explicação da afirmação 3.',
  },
  {
    id: '24',
    variant: 'two-line',
    lines: [
      'Ele não escreveu nada.',
      'Tudo o que sabemos dele chegou por terceiros.',
    ],
    steps: 2,
    note: '"E por que eu perguntei tanto em vez de explicar?" Sócrates, Atenas, século V a.C. Conhecemos por Platão, Xenofonte, Aristófanes — e isso é um problema epistemológico sobre o próprio Sócrates. É a resposta da afirmação 3.',
  },
  {
    id: '25',
    variant: 'two-line',
    lines: ['MAIÊUTICA', 'a arte da parteira — e o teste do ovo de vento'],
    steps: 2,
    note: 'Filho da parteira Fenarete. Não paria ideias, ajudava a parir — e depois testava se a ideia se sustentava ou era ovo de vento. A segunda metade é a que todo mundo esquece. E "só sei que nada sei" ele não disse.',
  },
  {
    id: '26',
    variant: 'versus',
    left: { term: 'EPISTEMOLOGIA', gloss: 'o que se investiga: o conhecimento' },
    right: { term: 'MAIÊUTICA', gloss: 'um como se investiga: pela pergunta' },
    steps: 3,
    note: 'NUNCA CORTA. Dá para fazer epistemologia sem maiêutica nenhuma, e dá para usar maiêutica para investigar justiça, coragem, qualquer coisa. Ela foi a ferramenta, não era o assunto.',
  },
  {
    id: '27',
    variant: 'mega',
    text: 'POR QUE UM PROFESSOR PRECISA PENSAR SOBRE ISSO?',
    steps: 1,
    note: 'Escute duas respostas, não hierarquize, costure: "todas essas estão dentro da mesma coisa". Se passou de 14:40, corte a pergunta e vire afirmação.',
  },
  {
    id: '28',
    variant: 'axis',
    left: 'EMPIRISMO',
    right: 'EPISTEMOLOGIA',
    caption: 'uma resposta · a pergunta que a torna necessária',
    foot: 'o que transforma percepção, experiência ou testemunho em conhecimento justificável?',
    steps: 2,
    note: 'A ponte, sem competição: o empirismo dá uma resposta importante, a de que o conhecimento vem da experiência. Não é resposta menor, é uma das grandes.',
  },
  {
    id: '29',
    variant: 'two-line',
    lines: [
      'Que tipo de conhecimento é este —',
      'e o que conta como saber isto?',
    ],
    foot: 'pergunta epistemológica, não metodológica',
    steps: 2,
    note: 'Não faça a versão fácil ("transmitir é ruim, construir é bom"): não é verdade e todo mundo já concorda. Depois desta tela, fale sem apoio: "eu escolhi começar com um problema e isso teve um preço".',
  },
  {
    id: '30',
    variant: 'thermometer',
    tag: 'Afirmação 2 · quem marcou verdadeiro',
    steps: 1,
    note: '16:30 · Depois do verso da ficha, pergunte de novo quem marca VERDADEIRO agora. Nunca comemore o número. As barras e a contagem entram no passo 6.',
  },
  {
    id: '31',
    variant: 'two-line',
    lines: [
      '"A Terra é redonda" e "10% do cérebro" não estão empatadas.',
      'O trabalho não é desistir de saber — é saber por quê.',
    ],
    steps: 2,
    note: 'OBRIGATÓRIA: é o que impede o seminário de terminar em relativismo barato. "Se a resposta for nada, aquilo não é conhecimento. É identidade." Nunca corte, mesmo estourando o tempo.',
  },
  {
    id: '32',
    variant: 'mega',
    text: 'Como você sabe que aquilo que você sabe é verdade?',
    steps: 1,
    note: 'Mesma pergunta do começo. "Faz dezoito minutos. Acho que a pergunta ficou mais difícil." Comece a distribuir os cartões agora, falando.',
  },
  {
    id: '33',
    variant: 'final',
    lines: [
      'A epistemologia não começa quando a gente duvida de tudo.',
      'Ela começa quando a gente para de perguntar só "o que eu sei?"',
      'e passa a perguntar: o que me autoriza a chamar isso de conhecimento?',
      'Obrigado.',
    ],
    steps: 4,
    note: 'No clique, nunca automático. A última linha entra depois de três segundos de silêncio.',
  },
  {
    id: '34',
    variant: 'eusei',
    text: 'EU SEI?',
    foot: 'as referências e as cinco perguntas',
    qr: 'luisfilipegdc.com.br/epistemologia',
    steps: 1,
    note: 'Fica no ar enquanto eles saem — é o tempo de leitura do QR. O QR de verdade entra no passo 5.',
  },
  {
    id: '35',
    variant: 'credits',
    tag: 'Seminário de Epistemologia · Pedagogia',
    names: ['Luis', 'Carlos', 'Malu', 'Renata', 'Rebeca', 'Mariana', 'Dalila'],
    steps: 1,
    note: 'Se a professora exigir identificação no início, mostre esta por três segundos antes da primeira e volte com Home.',
  },
]
